"""Train the building / tree point classifier and write it as VEX for Houdini.

Input : site-model/houdini/out/ml_sample.geo  (written by /obj/lidar/ml_sample_write: a sample of raised points with the
        f_* shape features from ml_features and the context labels from ml_labels: 0 building, 1 tree, -1 unlabelled)
Output: site-model/houdini/vex/seg_forest.vfl  a random forest as flat arrays + an evaluation loop; pasted into
        /obj/lidar/ml_predict (f@p_tree = share of trees voting "tree")

Labels come from location (inside a LARIAC footprint vs. next to a kept tree far from footprints), never from the
features, so the forest learns what a building or tree return looks like and can then judge the points in between.
Validation is grouped by 50 m blocks, so neighbouring points never sit on both sides of a split.

  python site-model/houdini/tools/train_seg_forest.py
"""
import json
from pathlib import Path

import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GroupKFold

HZ = Path(__file__).resolve().parent.parent
N_TREES, DEPTH, LEAF = 25, 8, 20


def geo_point_attribs(path):
    g = json.load(open(path))
    d = dict(zip(g[0::2], g[1::2]))
    att = dict(zip(d["attributes"][0::2], d["attributes"][1::2]))
    out = {}
    for meta, body in att["pointattributes"]:
        meta = dict(zip(meta[0::2], meta[1::2]))
        body = dict(zip(body[0::2], body[1::2]))
        vals = dict(zip(body["values"][0::2], body["values"][1::2]))
        out[meta["name"]] = np.asarray(vals["tuples"] if "tuples" in vals else vals["arrays"][0], dtype=float)
    return out


A = geo_point_attribs(HZ / "out" / "ml_sample.geo")
FEATS = sorted(k for k in A if k.startswith("f_"))
X = np.column_stack([A[k] for k in FEATS])
y, block = A["ml_label"].astype(int), A["ml_block"].astype(int)
lab = y >= 0
print(f"{len(y):,} sample points: building {np.sum(y == 0):,}, tree {np.sum(y == 1):,}, unlabelled {np.sum(y < 0):,}")
print("features:", ", ".join(FEATS))

rf_args = dict(n_estimators=N_TREES, max_depth=DEPTH, min_samples_leaf=LEAF, class_weight="balanced", n_jobs=-1, random_state=1)
pred = np.zeros(lab.sum())
for tr, te in GroupKFold(5).split(X[lab], y[lab], block[lab]):
    m = RandomForestClassifier(**rf_args).fit(X[lab][tr], y[lab][tr])
    pred[te] = m.predict_proba(X[lab][te])[:, 1]
yl = y[lab]
for name, c in (("building", 0), ("tree", 1)):
    sel = yl == c
    print(f"  block CV, {name}: {np.mean((pred[sel] >= 0.5) == c):.1%} correct")

rf = RandomForestClassifier(**rf_args).fit(X[lab], yl)
imp = sorted(zip(rf.feature_importances_, FEATS), reverse=True)
print("importance:", ", ".join(f"{f} {v:.3f}" for v, f in imp[:10]))
pu = rf.predict_proba(X[~lab])[:, 1]
seg = A["segc"][~lab].astype(int)
print("unlabelled sample, share called tree (p >= 0.5) by current segment:")
for s, nm in enumerate(["ground", "low", "building", "tree", "unsure", "podium_tree", "porous_facade"]):
    sel = seg == s
    if sel.any():
        print(f"  {nm:14s} {sel.sum():7,}  tree {np.mean(pu[sel] >= 0.5):.1%}")

# flatten the forest: one array per field, node ids offset per tree; leaves have feature -1 and carry p(tree)
feat, thr, left, right, val, roots = [], [], [], [], [], []
for est in rf.estimators_:
    t = est.tree_
    off = len(feat)
    roots.append(off)
    for i in range(t.node_count):
        leaf = t.children_left[i] < 0
        feat.append(-1 if leaf else int(t.feature[i]))
        thr.append(0.0 if leaf else float(t.threshold[i]))
        left.append(-1 if leaf else off + int(t.children_left[i]))
        right.append(-1 if leaf else off + int(t.children_right[i]))
        v = t.value[i][0]
        val.append(float(v[1] / v.sum()))


def arr(kind, xs, fmt):
    return f"{kind} {{" + ", ".join(fmt(x) for x in xs) + "}"


fl = lambda x: f"{x:.9g}"
reads = "\n".join(f'fv[{i}] = f@{k};' for i, k in enumerate(FEATS))
vex = f"""// Random forest building / tree classifier, generated by site-model/houdini/tools/train_seg_forest.py -- do not edit.
// {N_TREES} trees, depth <= {DEPTH}, {len(feat)} nodes, trained on {lab.sum():,} context-labelled sample points.
// f@p_tree = mean over the trees of the leaf's tree share (0 building ... 1 tree); raised points only.
f@p_tree = -1;
if (!i@ml_raised) return;
float fv[]; resize(fv, {len(FEATS)});
{reads}
int   nf[] = {arr('', feat, str)[1:]};
float nt[] = {arr('', thr, fl)[1:]};
int   nl[] = {arr('', left, str)[1:]};
int   nr[] = {arr('', right, str)[1:]};
float nv[] = {arr('', val, fl)[1:]};
int roots[] = {arr('', roots, str)[1:]};
float p = 0;
foreach (int r; roots) {{
    int k = r;
    while (nf[k] >= 0) k = fv[nf[k]] <= nt[k] ? nl[k] : nr[k];
    p += nv[k];
}}
f@p_tree = p / len(roots);
"""
out = HZ / "vex" / "seg_forest.vfl"
out.parent.mkdir(exist_ok=True)
out.write_text(vex)
print(f"-> {out} ({len(feat):,} nodes, {out.stat().st_size / 1e3:.0f} kB)")
